// AUTO-GENERATED by scripts/generate-routes.ts — do not edit by hand.
// Regenerated automatically by `npm run dev` and `npm run build`.
// To add a route: create a folder + route.ts under src/app/, then re-run.

import { Router } from 'express';
import { asyncHandler } from '@/utils/async-handler';

import * as route_0 from '../app/api/health/route';
import * as route_1 from '../app/api/users/[id]/route';
import * as route_2 from '../app/health/route';
import * as route_3 from '../app/route';
import * as route_4 from '../app/users/[id]/route';
import * as route_5 from '../app/users/route';

export function buildRoutes() {
  const router = Router();

  const m0 = route_0 as any;
  const m1 = route_1 as any;
  const m2 = route_2 as any;
  const m3 = route_3 as any;
  const m4 = route_4 as any;
  const m5 = route_5 as any;

  if (m0.GET) router.get("/api/health", asyncHandler(m0.GET));
  if (m0.POST) router.post("/api/health", asyncHandler(m0.POST));
  if (m0.PUT) router.put("/api/health", asyncHandler(m0.PUT));
  if (m0.PATCH) router.patch("/api/health", asyncHandler(m0.PATCH));
  if (m0.DELETE) router.delete("/api/health", asyncHandler(m0.DELETE));
  if (m1.GET) router.get("/api/users/:id", asyncHandler(m1.GET));
  if (m1.POST) router.post("/api/users/:id", asyncHandler(m1.POST));
  if (m1.PUT) router.put("/api/users/:id", asyncHandler(m1.PUT));
  if (m1.PATCH) router.patch("/api/users/:id", asyncHandler(m1.PATCH));
  if (m1.DELETE) router.delete("/api/users/:id", asyncHandler(m1.DELETE));
  if (m2.GET) router.get("/health", asyncHandler(m2.GET));
  if (m2.POST) router.post("/health", asyncHandler(m2.POST));
  if (m2.PUT) router.put("/health", asyncHandler(m2.PUT));
  if (m2.PATCH) router.patch("/health", asyncHandler(m2.PATCH));
  if (m2.DELETE) router.delete("/health", asyncHandler(m2.DELETE));
  if (m3.GET) router.get("/", asyncHandler(m3.GET));
  if (m3.POST) router.post("/", asyncHandler(m3.POST));
  if (m3.PUT) router.put("/", asyncHandler(m3.PUT));
  if (m3.PATCH) router.patch("/", asyncHandler(m3.PATCH));
  if (m3.DELETE) router.delete("/", asyncHandler(m3.DELETE));
  if (m4.GET) router.get("/users/:id", asyncHandler(m4.GET));
  if (m4.POST) router.post("/users/:id", asyncHandler(m4.POST));
  if (m4.PUT) router.put("/users/:id", asyncHandler(m4.PUT));
  if (m4.PATCH) router.patch("/users/:id", asyncHandler(m4.PATCH));
  if (m4.DELETE) router.delete("/users/:id", asyncHandler(m4.DELETE));
  if (m5.GET) router.get("/users", asyncHandler(m5.GET));
  if (m5.POST) router.post("/users", asyncHandler(m5.POST));
  if (m5.PUT) router.put("/users", asyncHandler(m5.PUT));
  if (m5.PATCH) router.patch("/users", asyncHandler(m5.PATCH));
  if (m5.DELETE) router.delete("/users", asyncHandler(m5.DELETE));

  return router;
}
