// This file is auto-generated. DO NOT EDIT.
// It will be regenerated by: npm run routes:generate

import { Router } from 'express';
import { asyncHandler } from '@/utils/async-handler';

export function buildRoutes() {
  const router = Router();
  // Routes will be generated here by scripts/generate-routes.ts
  return router;
}
