#!/usr/bin/env node
/**
 * Scans src/app/ for route.ts files and generates src/lib/routes.generated.ts
 * with plain, static `import` statements and explicit `router.get(...)` calls.
 *
 * Why generate instead of scanning the filesystem at runtime?
 * Bundlers used by serverless hosts (Vercel, AWS Lambda, etc.) trace *static*
 * imports to decide which files ship in the deployed function. Runtime
 * `fs.readdirSync` + dynamic `import()` isn't traceable, so route files can
 * silently go missing in production. A generated, fully static file fixes
 * that — while still giving you the "folder = route" authoring experience.
 *
 * Runs automatically before `npm run dev` and `npm run build`.
 * Run manually any time with: npm run routes:generate
 */
import { readdirSync, statSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const APP_DIR = join(ROOT, 'src', 'app');
const LIB_DIR = join(ROOT, 'src', 'lib');
const OUT_FILE = join(LIB_DIR, 'routes.generated.ts');

const HTTP_METHODS = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'];
const DYNAMIC_SEGMENT = /^\[(.+)\]$/; // "[id]" -> "id"

function findRouteFiles(dir) {
  const files = [];
  for (const entry of readdirSync(dir)) {
    const fullPath = join(dir, entry);
    if (statSync(fullPath).isDirectory()) {
      files.push(...findRouteFiles(fullPath));
    } else if (entry === 'route.ts') {
      files.push(fullPath);
    }
  }
  return files;
}

function toExpressPath(routeFile) {
  const segments = relative(APP_DIR, dirname(routeFile)).split(sep).filter(Boolean);
  const expressSegments = segments.map((segment) => {
    const match = segment.match(DYNAMIC_SEGMENT);
    return match ? `:${match[1]}` : segment;
  });
  return '/' + expressSegments.join('/');
}

function toImportSpecifier(routeFile) {
  const rel = relative(LIB_DIR, routeFile).split(sep).join('/').replace(/\.ts$/, '.js');
  return rel.startsWith('.') ? rel : `./${rel}`;
}

const routeFiles = findRouteFiles(APP_DIR).sort();

const imports = routeFiles.map(
  (file, i) => `import * as route_${i} from '${toImportSpecifier(file)}';`,
);

const registrations = routeFiles.flatMap((file, i) => {
  const path = toExpressPath(file);
  return HTTP_METHODS.map(
    (method) =>
      `  if (m${i}.${method}) router.${method.toLowerCase()}(${JSON.stringify(path)}, m${i}.${method});`,
  );
});

const moduleCasts = routeFiles.map((_, i) => `  const m${i} = route_${i} as RouteModule;`);

const content = `// AUTO-GENERATED by scripts/generate-routes.mjs — do not edit by hand.
// Regenerated automatically by \`npm run dev\` and \`npm run build\`.
// To add a route: create a folder + route.ts under src/app/, then re-run
// \`npm run routes:generate\` (or just restart npm run dev / npm run build).

import { Router, type Request, type Response, type NextFunction } from 'express';
${imports.join('\n')}

type Handler = (req: Request, res: Response, next: NextFunction) => unknown;
type RouteModule = Record<string, Handler | undefined>;

export function buildRoutes(): Router {
  const router = Router();
${moduleCasts.join('\n')}

${registrations.join('\n')}

  return router;
}
`;

mkdirSync(LIB_DIR, { recursive: true });
writeFileSync(OUT_FILE, content);

console.log(`Generated ${routeFiles.length} route(s):`);
for (const file of routeFiles) {
  console.log(`  ${toExpressPath(file)}  <-  ${relative(APP_DIR, file)}`);
}
