#!/usr/bin/env node
import { readdirSync, statSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const APP_DIR = join(ROOT, 'src', 'app');
const LIB_DIR = join(ROOT, 'src', 'lib');
const OUT_FILE = join(LIB_DIR, 'routes.generated.ts');

const HTTP_METHODS = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'];
const DYNAMIC_SEGMENT = /^\[(.+)\]$/; // "[id]" -> "id"

function findRouteFiles(dir) {
  const files = [];
  try {
    for (const entry of readdirSync(dir)) {
      const fullPath = join(dir, entry);
      if (statSync(fullPath).isDirectory()) {
        files.push(...findRouteFiles(fullPath));
      } else if (entry === 'route.ts') {
        files.push(fullPath);
      }
    }
  } catch (err) {
    // Directory doesn't exist yet
  }
  return files;
}

function toExpressPath(routeFile) {
  const segments = relative(APP_DIR, dirname(routeFile)).split(sep).filter(Boolean);
  const expressSegments = segments.map((segment) => {
    const match = segment.match(DYNAMIC_SEGMENT);
    return match ? `:${match[1]}` : segment;
  });
  return '/' + expressSegments.join('/');
}

function toImportSpecifier(routeFile) {
  const rel = relative(LIB_DIR, routeFile).split(sep).join('/').replace(/\.ts$/, '.js');
  return rel.startsWith('.') ? rel : `./${rel}`;
}

const routeFiles = findRouteFiles(APP_DIR).sort();

if (!routeFiles.length) {
  console.log('No routes found, generating empty routes file...');
}

const imports = routeFiles.map(
  (file, i) => `import * as route_${i} from '${toImportSpecifier(file)}';`,
);

const registrations = routeFiles.flatMap((file, i) => {
  const path = toExpressPath(file);
  return HTTP_METHODS.map(
    (method) =>
      `  if (m${i}.${method}) router.${method.toLowerCase()}(${JSON.stringify(path)}, asyncHandler(m${i}.${method}));`,
  );
});

const moduleCasts = routeFiles.map((_, i) => `  const m${i} = route_${i} as any;`);

const content = `// AUTO-GENERATED by scripts/generate-routes.mjs — do not edit by hand.
// Regenerated automatically by \`npm run dev\` and \`npm run build\`.
// To add a route: create a folder + route.ts under src/app/, then re-run.

import { Router } from 'express';
import { asyncHandler } from '@/utils/async-handler.js';

${imports.join('\n')}

export function buildRoutes() {
  const router = Router();

${moduleCasts.join('\n')}

${registrations.join('\n')}

  return router;
}
`;

try {
  mkdirSync(dirname(OUT_FILE), { recursive: true });
  writeFileSync(OUT_FILE, content, 'utf-8');
  console.log(`✅ Routes generated: ${routeFiles.length} routes found`);
} catch (err) {
  console.error('Error generating routes:', err);
  process.exit(1);
}
